language: objective-c
#xcode_project: CKPromise.Swift.xcodeproj
#xcode_scheme: CKPromise.Swift
osx_image: xcode8

script:
- set -o pipefail
- xcodebuild test -project CKPromise.Swift.xcodeproj -scheme CKPromise.Swift -sdk iphonesimulator | xcpretty
